/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-postgres'
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  timestamp,
  serial,
  numeric,
  boolean,
  jsonb,
  pgEnum,
} from '@payloadcms/db-postgres/drizzle/pg-core'
import { sql, relations } from '@payloadcms/db-postgres/drizzle'
export const enum_users_role = pgEnum('enum_users_role', ['admin', 'user'])
export const enum_users_currency = pgEnum('enum_users_currency', ['VND', 'USD'])
export const enum_wallets_wallet_type = pgEnum('enum_wallets_wallet_type', [
  'main',
  'cash',
  'bank',
  'savings',
])
export const enum_categories_type = pgEnum('enum_categories_type', ['income', 'expense'])
export const enum_transactions_type = pgEnum('enum_transactions_type', ['income', 'expense'])
export const enum_transactions_source_type = pgEnum('enum_transactions_source_type', [
  'manual',
  'chatbot',
  'receipt_ai',
  'transfer',
  'adjustment',
])
export const enum_budgets_period = pgEnum('enum_budgets_period', [
  'daily',
  'weekly',
  'monthly',
  'yearly',
])
export const enum_savings_goals_status = pgEnum('enum_savings_goals_status', [
  'active',
  'completed',
])
export const enum_notifications_type = pgEnum('enum_notifications_type', [
  'invitation',
  'contribution',
  'completion',
  'system',
])

export const users_sessions = pgTable(
  'users_sessions',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
    expiresAt: timestamp('expires_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index('users_sessions_order_idx').on(columns._order),
    index('users_sessions_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [users.id],
      name: 'users_sessions_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const users = pgTable(
  'users',
  {
    id: serial('id').primaryKey(),
    role: enum_users_role('role').notNull().default('user'),
    name: varchar('name'),
    currency: enum_users_currency('currency').default('VND'),
    avatar: integer('avatar_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    email: varchar('email').notNull(),
    resetPasswordToken: varchar('reset_password_token'),
    resetPasswordExpiration: timestamp('reset_password_expiration', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar('salt'),
    hash: varchar('hash'),
    loginAttempts: numeric('login_attempts', { mode: 'number' }).default(0),
    lockUntil: timestamp('lock_until', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => [
    index('users_avatar_idx').on(columns.avatar),
    index('users_updated_at_idx').on(columns.updatedAt),
    index('users_created_at_idx').on(columns.createdAt),
    uniqueIndex('users_email_idx').on(columns.email),
  ],
)

export const media = pgTable(
  'media',
  {
    id: serial('id').primaryKey(),
    alt: varchar('alt').notNull(),
    ownerId: numeric('owner_id', { mode: 'number' }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize', { mode: 'number' }),
    width: numeric('width', { mode: 'number' }),
    height: numeric('height', { mode: 'number' }),
    focalX: numeric('focal_x', { mode: 'number' }),
    focalY: numeric('focal_y', { mode: 'number' }),
  },
  (columns) => [
    index('media_updated_at_idx').on(columns.updatedAt),
    index('media_created_at_idx').on(columns.createdAt),
    uniqueIndex('media_filename_idx').on(columns.filename),
  ],
)

export const wallets = pgTable(
  'wallets',
  {
    id: serial('id').primaryKey(),
    user: integer('user_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null',
      }),
    name: varchar('name').notNull(),
    walletType: enum_wallets_wallet_type('wallet_type').notNull().default('cash'),
    currency: varchar('currency').notNull().default('VND'),
    balance: numeric('balance', { mode: 'number' }).notNull().default(0),
    monthlySpendingLimit: numeric('monthly_spending_limit', { mode: 'number' }),
    isDefault: boolean('is_default').default(false),
    isActive: boolean('is_active').default(true),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('wallets_user_idx').on(columns.user),
    index('wallets_updated_at_idx').on(columns.updatedAt),
    index('wallets_created_at_idx').on(columns.createdAt),
  ],
)

export const categories = pgTable(
  'categories',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    type: enum_categories_type('type').notNull(),
    icon: varchar('icon').default('Package'),
    note: varchar('note'),
    color: varchar('color').default('#6366f1'),
    user: integer('user_id').references(() => users.id, {
      onDelete: 'set null',
    }),
    isDefault: boolean('is_default').default(false),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('categories_user_idx').on(columns.user),
    index('categories_updated_at_idx').on(columns.updatedAt),
    index('categories_created_at_idx').on(columns.createdAt),
  ],
)

export const transactions = pgTable(
  'transactions',
  {
    id: serial('id').primaryKey(),
    type: enum_transactions_type('type').notNull(),
    amount: numeric('amount', { mode: 'number' }).notNull(),
    merchantName: varchar('merchant_name'),
    currency: varchar('currency').default('VND'),
    wallet: integer('wallet_id')
      .notNull()
      .references(() => wallets.id, {
        onDelete: 'set null',
      }),
    category: integer('category_id')
      .notNull()
      .references(() => categories.id, {
        onDelete: 'set null',
      }),
    description: varchar('description'),
    date: timestamp('date', { mode: 'string', withTimezone: true, precision: 3 }).notNull(),
    note: varchar('note'),
    receipt: integer('receipt_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    sourceType: enum_transactions_source_type('source_type').default('manual'),
    sourceRefId: varchar('source_ref_id'),
    savingsGoal: integer('savings_goal_id').references(() => savings_goals.id, {
      onDelete: 'set null',
    }),
    user: integer('user_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null',
      }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('transactions_type_idx').on(columns.type),
    index('transactions_wallet_idx').on(columns.wallet),
    index('transactions_category_idx').on(columns.category),
    index('transactions_date_idx').on(columns.date),
    index('transactions_receipt_idx').on(columns.receipt),
    index('transactions_source_type_idx').on(columns.sourceType),
    index('transactions_savings_goal_idx').on(columns.savingsGoal),
    index('transactions_user_idx').on(columns.user),
    index('transactions_updated_at_idx').on(columns.updatedAt),
    index('transactions_created_at_idx').on(columns.createdAt),
  ],
)

export const budgets = pgTable(
  'budgets',
  {
    id: serial('id').primaryKey(),
    wallet: integer('wallet_id').references(() => wallets.id, {
      onDelete: 'set null',
    }),
    category: integer('category_id')
      .notNull()
      .references(() => categories.id, {
        onDelete: 'set null',
      }),
    amount: numeric('amount', { mode: 'number' }).notNull(),
    period: enum_budgets_period('period').notNull().default('monthly'),
    month: numeric('month', { mode: 'number' }),
    year: numeric('year', { mode: 'number' }),
    note: varchar('note'),
    alertThresholds: jsonb('alert_thresholds').default(sql`'[80,100]'::jsonb`),
    isActive: boolean('is_active').default(true),
    user: integer('user_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null',
      }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('budgets_wallet_idx').on(columns.wallet),
    index('budgets_category_idx').on(columns.category),
    index('budgets_period_idx').on(columns.period),
    index('budgets_month_idx').on(columns.month),
    index('budgets_year_idx').on(columns.year),
    index('budgets_is_active_idx').on(columns.isActive),
    index('budgets_user_idx').on(columns.user),
    index('budgets_updated_at_idx').on(columns.updatedAt),
    index('budgets_created_at_idx').on(columns.createdAt),
  ],
)

export const savings_goals = pgTable(
  'savings_goals',
  {
    id: serial('id').primaryKey(),
    title: varchar('title').notNull(),
    targetAmount: numeric('target_amount', { mode: 'number' }).notNull(),
    currentAmount: numeric('current_amount', { mode: 'number' }).default(0),
    status: enum_savings_goals_status('status').default('active'),
    icon: varchar('icon').default('Target'),
    color: varchar('color').default('#6366f1'),
    owner: integer('owner_id').references(() => users.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('savings_goals_owner_idx').on(columns.owner),
    index('savings_goals_updated_at_idx').on(columns.updatedAt),
    index('savings_goals_created_at_idx').on(columns.createdAt),
  ],
)

export const savings_goals_rels = pgTable(
  'savings_goals_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
  },
  (columns) => [
    index('savings_goals_rels_order_idx').on(columns.order),
    index('savings_goals_rels_parent_idx').on(columns.parent),
    index('savings_goals_rels_path_idx').on(columns.path),
    index('savings_goals_rels_users_id_idx').on(columns.usersID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [savings_goals.id],
      name: 'savings_goals_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'savings_goals_rels_users_fk',
    }).onDelete('cascade'),
  ],
)

export const notifications = pgTable(
  'notifications',
  {
    id: serial('id').primaryKey(),
    recipient: integer('recipient_id')
      .notNull()
      .references(() => users.id, {
        onDelete: 'set null',
      }),
    message: varchar('message').notNull(),
    type: enum_notifications_type('type').notNull(),
    read: boolean('read').default(false),
    link: varchar('link'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('notifications_recipient_idx').on(columns.recipient),
    index('notifications_updated_at_idx').on(columns.updatedAt),
    index('notifications_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_kv = pgTable(
  'payload_kv',
  {
    id: serial('id').primaryKey(),
    key: varchar('key').notNull(),
    data: jsonb('data').notNull(),
  },
  (columns) => [uniqueIndex('payload_kv_key_idx').on(columns.key)],
)

export const payload_locked_documents = pgTable(
  'payload_locked_documents',
  {
    id: serial('id').primaryKey(),
    globalSlug: varchar('global_slug'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_locked_documents_global_slug_idx').on(columns.globalSlug),
    index('payload_locked_documents_updated_at_idx').on(columns.updatedAt),
    index('payload_locked_documents_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_locked_documents_rels = pgTable(
  'payload_locked_documents_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
    mediaID: integer('media_id'),
    walletsID: integer('wallets_id'),
    categoriesID: integer('categories_id'),
    transactionsID: integer('transactions_id'),
    budgetsID: integer('budgets_id'),
    'savings-goalsID': integer('savings_goals_id'),
    notificationsID: integer('notifications_id'),
  },
  (columns) => [
    index('payload_locked_documents_rels_order_idx').on(columns.order),
    index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    index('payload_locked_documents_rels_path_idx').on(columns.path),
    index('payload_locked_documents_rels_users_id_idx').on(columns.usersID),
    index('payload_locked_documents_rels_media_id_idx').on(columns.mediaID),
    index('payload_locked_documents_rels_wallets_id_idx').on(columns.walletsID),
    index('payload_locked_documents_rels_categories_id_idx').on(columns.categoriesID),
    index('payload_locked_documents_rels_transactions_id_idx').on(columns.transactionsID),
    index('payload_locked_documents_rels_budgets_id_idx').on(columns.budgetsID),
    index('payload_locked_documents_rels_savings_goals_id_idx').on(columns['savings-goalsID']),
    index('payload_locked_documents_rels_notifications_id_idx').on(columns.notificationsID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['walletsID']],
      foreignColumns: [wallets.id],
      name: 'payload_locked_documents_rels_wallets_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['categoriesID']],
      foreignColumns: [categories.id],
      name: 'payload_locked_documents_rels_categories_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['transactionsID']],
      foreignColumns: [transactions.id],
      name: 'payload_locked_documents_rels_transactions_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['budgetsID']],
      foreignColumns: [budgets.id],
      name: 'payload_locked_documents_rels_budgets_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['savings-goalsID']],
      foreignColumns: [savings_goals.id],
      name: 'payload_locked_documents_rels_savings_goals_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['notificationsID']],
      foreignColumns: [notifications.id],
      name: 'payload_locked_documents_rels_notifications_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_preferences = pgTable(
  'payload_preferences',
  {
    id: serial('id').primaryKey(),
    key: varchar('key'),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_preferences_key_idx').on(columns.key),
    index('payload_preferences_updated_at_idx').on(columns.updatedAt),
    index('payload_preferences_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_preferences_rels = pgTable(
  'payload_preferences_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
  },
  (columns) => [
    index('payload_preferences_rels_order_idx').on(columns.order),
    index('payload_preferences_rels_parent_idx').on(columns.parent),
    index('payload_preferences_rels_path_idx').on(columns.path),
    index('payload_preferences_rels_users_id_idx').on(columns.usersID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_migrations = pgTable(
  'payload_migrations',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    batch: numeric('batch', { mode: 'number' }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_migrations_updated_at_idx').on(columns.updatedAt),
    index('payload_migrations_created_at_idx').on(columns.createdAt),
  ],
)

export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
  _parentID: one(users, {
    fields: [users_sessions._parentID],
    references: [users.id],
    relationName: 'sessions',
  }),
}))
export const relations_users = relations(users, ({ one, many }) => ({
  avatar: one(media, {
    fields: [users.avatar],
    references: [media.id],
    relationName: 'avatar',
  }),
  sessions: many(users_sessions, {
    relationName: 'sessions',
  }),
}))
export const relations_media = relations(media, () => ({}))
export const relations_wallets = relations(wallets, ({ one }) => ({
  user: one(users, {
    fields: [wallets.user],
    references: [users.id],
    relationName: 'user',
  }),
}))
export const relations_categories = relations(categories, ({ one }) => ({
  user: one(users, {
    fields: [categories.user],
    references: [users.id],
    relationName: 'user',
  }),
}))
export const relations_transactions = relations(transactions, ({ one }) => ({
  wallet: one(wallets, {
    fields: [transactions.wallet],
    references: [wallets.id],
    relationName: 'wallet',
  }),
  category: one(categories, {
    fields: [transactions.category],
    references: [categories.id],
    relationName: 'category',
  }),
  receipt: one(media, {
    fields: [transactions.receipt],
    references: [media.id],
    relationName: 'receipt',
  }),
  savingsGoal: one(savings_goals, {
    fields: [transactions.savingsGoal],
    references: [savings_goals.id],
    relationName: 'savingsGoal',
  }),
  user: one(users, {
    fields: [transactions.user],
    references: [users.id],
    relationName: 'user',
  }),
}))
export const relations_budgets = relations(budgets, ({ one }) => ({
  wallet: one(wallets, {
    fields: [budgets.wallet],
    references: [wallets.id],
    relationName: 'wallet',
  }),
  category: one(categories, {
    fields: [budgets.category],
    references: [categories.id],
    relationName: 'category',
  }),
  user: one(users, {
    fields: [budgets.user],
    references: [users.id],
    relationName: 'user',
  }),
}))
export const relations_savings_goals_rels = relations(savings_goals_rels, ({ one }) => ({
  parent: one(savings_goals, {
    fields: [savings_goals_rels.parent],
    references: [savings_goals.id],
    relationName: '_rels',
  }),
  usersID: one(users, {
    fields: [savings_goals_rels.usersID],
    references: [users.id],
    relationName: 'users',
  }),
}))
export const relations_savings_goals = relations(savings_goals, ({ one, many }) => ({
  owner: one(users, {
    fields: [savings_goals.owner],
    references: [users.id],
    relationName: 'owner',
  }),
  _rels: many(savings_goals_rels, {
    relationName: '_rels',
  }),
}))
export const relations_notifications = relations(notifications, ({ one }) => ({
  recipient: one(users, {
    fields: [notifications.recipient],
    references: [users.id],
    relationName: 'recipient',
  }),
}))
export const relations_payload_kv = relations(payload_kv, () => ({}))
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: 'media',
    }),
    walletsID: one(wallets, {
      fields: [payload_locked_documents_rels.walletsID],
      references: [wallets.id],
      relationName: 'wallets',
    }),
    categoriesID: one(categories, {
      fields: [payload_locked_documents_rels.categoriesID],
      references: [categories.id],
      relationName: 'categories',
    }),
    transactionsID: one(transactions, {
      fields: [payload_locked_documents_rels.transactionsID],
      references: [transactions.id],
      relationName: 'transactions',
    }),
    budgetsID: one(budgets, {
      fields: [payload_locked_documents_rels.budgetsID],
      references: [budgets.id],
      relationName: 'budgets',
    }),
    'savings-goalsID': one(savings_goals, {
      fields: [payload_locked_documents_rels['savings-goalsID']],
      references: [savings_goals.id],
      relationName: 'savings-goals',
    }),
    notificationsID: one(notifications, {
      fields: [payload_locked_documents_rels.notificationsID],
      references: [notifications.id],
      relationName: 'notifications',
    }),
  }),
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  }),
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
  }),
)
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))

type DatabaseSchema = {
  enum_users_role: typeof enum_users_role
  enum_users_currency: typeof enum_users_currency
  enum_wallets_wallet_type: typeof enum_wallets_wallet_type
  enum_categories_type: typeof enum_categories_type
  enum_transactions_type: typeof enum_transactions_type
  enum_transactions_source_type: typeof enum_transactions_source_type
  enum_budgets_period: typeof enum_budgets_period
  enum_savings_goals_status: typeof enum_savings_goals_status
  enum_notifications_type: typeof enum_notifications_type
  users_sessions: typeof users_sessions
  users: typeof users
  media: typeof media
  wallets: typeof wallets
  categories: typeof categories
  transactions: typeof transactions
  budgets: typeof budgets
  savings_goals: typeof savings_goals
  savings_goals_rels: typeof savings_goals_rels
  notifications: typeof notifications
  payload_kv: typeof payload_kv
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  relations_users_sessions: typeof relations_users_sessions
  relations_users: typeof relations_users
  relations_media: typeof relations_media
  relations_wallets: typeof relations_wallets
  relations_categories: typeof relations_categories
  relations_transactions: typeof relations_transactions
  relations_budgets: typeof relations_budgets
  relations_savings_goals_rels: typeof relations_savings_goals_rels
  relations_savings_goals: typeof relations_savings_goals
  relations_notifications: typeof relations_notifications
  relations_payload_kv: typeof relations_payload_kv
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
}

declare module '@payloadcms/db-postgres' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
