BEGIN;

CREATE TABLE IF NOT EXISTS public.wallets (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    name character varying(120) NOT NULL,
    wallet_type character varying(50) NOT NULL DEFAULT 'cash',
    currency character varying(10) NOT NULL DEFAULT 'VND',
    balance numeric NOT NULL DEFAULT 0,
    is_default boolean NOT NULL DEFAULT false,
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    created_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS wallets_user_id_idx ON public.wallets (user_id);
CREATE UNIQUE INDEX IF NOT EXISTS wallets_single_default_per_user_idx
    ON public.wallets (user_id)
    WHERE is_default = true;

CREATE TABLE IF NOT EXISTS public.receipts (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    file_name character varying(255) NOT NULL,
    image_url text NOT NULL,
    mime_type character varying(100),
    file_size numeric,
    image_hash character varying(128),
    status character varying(30) NOT NULL DEFAULT 'uploaded',
    uploaded_at timestamp with time zone NOT NULL DEFAULT now(),
    processed_at timestamp with time zone,
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    created_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS receipts_user_id_idx ON public.receipts (user_id);
CREATE INDEX IF NOT EXISTS receipts_status_idx ON public.receipts (status);

CREATE TABLE IF NOT EXISTS public.receipt_parser_results (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_id integer NOT NULL REFERENCES public.receipts(id) ON DELETE CASCADE,
    provider character varying(100) NOT NULL,
    raw_text text,
    provider_json jsonb,
    normalized_json jsonb,
    suggested_category_id integer REFERENCES public.categories(id) ON DELETE SET NULL,
    suggested_description text,
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT receipt_parser_results_receipt_id_unique UNIQUE (receipt_id)
);

CREATE INDEX IF NOT EXISTS receipt_parser_results_suggested_category_idx
    ON public.receipt_parser_results (suggested_category_id);

ALTER TABLE public.transactions
    ADD COLUMN IF NOT EXISTS wallet_id integer,
    ADD COLUMN IF NOT EXISTS merchant_name character varying(255),
    ADD COLUMN IF NOT EXISTS source_type character varying(50),
    ADD COLUMN IF NOT EXISTS source_ref_id character varying(255);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'transactions_wallet_id_fkey'
    ) THEN
        ALTER TABLE public.transactions
            ADD CONSTRAINT transactions_wallet_id_fkey
            FOREIGN KEY (wallet_id) REFERENCES public.wallets(id) ON DELETE SET NULL;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'transactions_receipt_id_fkey'
    ) THEN
        ALTER TABLE public.transactions
            ADD CONSTRAINT transactions_receipt_id_fkey
            FOREIGN KEY (receipt_id) REFERENCES public.receipts(id) ON DELETE SET NULL;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS transactions_wallet_id_idx ON public.transactions (wallet_id);
CREATE INDEX IF NOT EXISTS transactions_receipt_id_idx ON public.transactions (receipt_id);
CREATE INDEX IF NOT EXISTS transactions_merchant_name_idx ON public.transactions (merchant_name);
CREATE INDEX IF NOT EXISTS transactions_source_type_idx ON public.transactions (source_type);

COMMIT;
